list:
  - t_300.hf
  - t_400.hf
  - t_1200.hf
  - t_1500.hf
  - t_1800.hf
  - t_1850.hf
  - t_1900.hf
  - t_1950.hf
  - t_2000.hf
  - t_2050.hf
  - t_2100.hf
  - t_2150.hf
  - t_2200.hf
  - t_2250.hf
  - t_2300.hf
  - t_2350.hf
  - t_2400.hf
profile_idx_size: 17
profile_idx:
  - run_param: 0
    suction: 0
    normal: 1
    large: 0
    orval: 0
    dia45: 0
    dia45_2: 0
    dia135: 0
    dia135_2: 0
    dia90: 0
  - run_param: 1
    suction: 0
    normal: 1
    large: 1
    orval: 1
    dia45: 1
    dia45_2: 1
    dia135: 1
    dia135_2: 1
    dia90: 1
  - run_param: 2
    suction: 1
    normal: 1
    large: 2
    orval: 2
    dia45: 2
    dia45_2: 2
    dia135: 2
    dia135_2: 2
    dia90: 2
  - run_param: 3
    suction: 2
    normal: 1
    large: 3
    orval: 3
    dia45: 3
    dia45_2: 3
    dia135: 3
    dia135_2: 3
    dia90: 3
  - run_param: 4
    suction: 2
    normal: 1
    large: 4
    orval: 4
    dia45: 4
    dia45_2: 4
    dia135: 4
    dia135_2: 4
    dia90: 4
  - run_param: 5
    suction: 2
    normal: 1
    large: 4
    orval: 4
    dia45: 4
    dia45_2: 4
    dia135: 4
    dia135_2: 4
    dia90: 4
  - run_param: 6
    suction: 2
    normal: 1
    large: 8
    orval: 8
    dia45: 6
    dia45_2: 6
    dia135: 6
    dia135_2: 6
    dia90: 6
  - run_param: 7
    suction: 2
    normal: 1
    large: 8
    orval: 8
    dia45: 6
    dia45_2: 6
    dia135: 6
    dia135_2: 6
    dia90: 6
  - run_param: 8
    suction: 2
    normal: 1
    large: 8
    orval: 8
    dia45: 6
    dia45_2: 6
    dia135: 6
    dia135_2: 6
    dia90: 6
  - run_param: 9
    suction: 2
    normal: 1
    large: 10
    orval: 10
    dia45: 8
    dia45_2: 8
    dia135: 8
    dia135_2: 8
    dia90: 6
  - run_param: 10
    suction: 2
    normal: 1
    large: 10
    orval: 10
    dia45: 8
    dia45_2: 8
    dia135: 8
    dia135_2: 8
    dia90: 6
  - run_param: 11
    suction: 2
    normal: 1
    large: 12
    orval: 10
    dia45: 8
    dia45_2: 8
    dia135: 8
    dia135_2: 8
    dia90: 6
  - run_param: 12
    suction: 2
    normal: 1
    large: 12
    orval: 10
    dia45: 8
    dia45_2: 8
    dia135: 8
    dia135_2: 8
    dia90: 6
  - run_param: 13
    suction: 2
    normal: 1
    large: 12
    orval: 10
    dia45: 8
    dia45_2: 8
    dia135: 8
    dia135_2: 8
    dia90: 6
  - run_param: 14
    suction: 2
    normal: 1
    large: 12
    orval: 10
    dia45: 8
    dia45_2: 8
    dia135: 8
    dia135_2: 8
    dia90: 6
  - run_param: 15
    suction: 2
    normal: 1
    large: 12
    orval: 10
    dia45: 8
    dia45_2: 8
    dia135: 8
    dia135_2: 8
    dia90: 6
  - run_param: 16
    suction: 2
    normal: 1
    large: 12
    orval: 10
    dia45: 8
    dia45_2: 8
    dia135: 8
    dia135_2: 8
    dia90: 6