list: [
    "t_300.hf", #0
    "t_400.hf", #1
    "t_1200.hf", #2
    "t_1500.hf", #3
    "t_1800.hf", #4
    "t_1850.hf", #5
    "t_1900.hf", #6
    "t_1950.hf", #7
    "t_2000.hf", #8
    "t_2050.hf", #9
    "t_2100.hf", #10
    "t_2150.hf", #11
    "t_2200.hf", #12
    "t_2250.hf", #13
    "t_2300.hf", #14
    "t_2350.hf", #15
    "t_2400.hf", #16
  ]
# 限界性能
# Large: 1800
# Orval: 1500
# 45: 1200 ~ 1350
# 135: ~1800
# 45_2: ~1550
# 135_2: ~1500
# V90: 1200　1150?
profile_idx_size: 19
# idx = mode選択時
profile_idx: [
    {
      # 0: 探索パラメータindex&最短 300
      run_param: 0,
      suction: 0,
      normal: 0,
      large: 0,
      orval: 0,
      dia45: 0,
      dia45_2: 0,
      dia135: 0,
      dia135_2: 0,
      dia90: 0,
    },
    {
      # 1: 最短パラメータ 400
      run_param: 1,
      suction: 0,
      normal: 1,
      large: 1,
      orval: 1,
      dia45: 1,
      dia45_2: 1,
      dia135: 1,
      dia135_2: 1,
      dia90: 1,
    },
    {
      # 2: 最短パラメータ 1200
      run_param: 2,
      suction: 1,
      normal: 0,
      large: 2,
      orval: 2,
      dia45: 2,
      dia45_2: 2,
      dia135: 2,
      dia135_2: 2,
      dia90: 2,
    },
    {
      # 3: 最短パラメータ 1500
      run_param: 3,
      suction: 2,
      normal: 0,
      large: 3,
      orval: 3,
      dia45: 3,
      dia45_2: 3,
      dia135: 3,
      dia135_2: 3,
      dia90: 3,
    },
    {
      # 4: 最短パラメータ 1800
      run_param: 4,
      suction: 2,
      normal: 0,
      large: 4,
      orval: 4,
      dia45: 4,
      dia45_2: 4,
      dia135: 4,
      dia135_2: 4,
      dia90: 4,
    },
    {
      # 5: 最短パラメータ 1850
      run_param: 5,
      suction: 2,
      normal: 0,
      large: 4,
      orval: 4,
      dia45: 4,
      dia45_2: 4,
      dia135: 4,
      dia135_2: 4,
      dia90: 4,
    },
    {
      # 6: 最短パラメータ 1900
      run_param: 6,
      suction: 2,
      normal: 0,
      large: 8,
      orval: 8,
      dia45: 8,
      dia45_2: 8,
      dia135: 6,
      dia135_2: 6,
      dia90: 5,
    },
    {
      # 7: 最短パラメータ 1950
      run_param: 7,
      suction: 2,
      normal: 0,
      large: 8,
      orval: 8,
      dia45: 8,
      dia45_2: 8,
      dia135: 6,
      dia135_2: 6,
      dia90: 6,
    },
    {
      # 8: 最短パラメータ 2000
      run_param: 8,
      suction: 2,
      normal: 0,
      large: 8,
      orval: 8,
      dia45: 8,
      dia45_2: 8,
      dia135: 6,
      dia135_2: 6,
      dia90: 6, 
    },
    {
      # 9: 最短パラメータ 2050
      run_param: 9,
      suction: 2,
      normal: 0,
      large: 9,
      orval: 9,
      dia45: 9,
      dia45_2: 9,
      dia135: 6,
      dia135_2: 6,
      dia90: 6,
    },
    {
      # 10: 最短パラメータ 2100
      run_param: 10,
      suction: 2,
      normal: 0,
      large: 10,
      orval: 10,
      dia45: 10,
      dia45_2: 10,
      dia135: 6,
      dia135_2: 6,
      dia90: 6,
    },
    {
      # 11: 最短パラメータ 2150
      run_param: 11,
      suction: 2,
      normal: 0,
      large: 11,
      orval: 11,
      dia45: 11,
      dia45_2: 11,
      dia135: 6,
      dia135_2: 6,
      dia90: 6,
    },
    {
      # 12: 最短パラメータ 2200
      run_param: 12,
      suction: 2,
      normal: 0,
      large: 12,
      orval: 12,
      dia45: 12,
      dia45_2: 12,
      dia135: 6,
      dia135_2: 6,
      dia90: 6, 
    },
    {
      # 13: 最短パラメータ 2250
      run_param: 13,
      suction: 2,
      normal: 0,
      large: 13,
      orval: 13,
      dia45: 13,
      dia45_2: 13,
      dia135: 6,
      dia135_2: 6,
      dia90: 6,
    },
    {
      # 14: 最短パラメータ 2300
      run_param: 14,
      suction: 2,
      normal: 0,
      large: 14,
      orval: 14,
      dia45: 14,    
      dia45_2: 14,
      dia135: 6,
      dia135_2: 6,
      dia90: 6,
    },
    {
      # 15: 最短パラメータ 2350
      run_param: 15,
      suction: 2,
      normal: 0,
      large: 15,
      orval: 15,
      dia45: 15,
      dia45_2: 15,
      dia135: 6,
      dia135_2: 6,
      dia90: 6,
    },
    {
      # 16: 最短パラメータ 2400
      run_param: 16,
      suction: 2,
      normal: 0,
      large: 16,
      orval: 16,
      dia45: 16,
      dia45_2: 16,
      dia135: 6,
      dia135_2: 6,
      dia90: 6,
    }
  ]
