list: [
    "t_300.hf", #0
    "t_400.hf", #1
    "t_500.hf", #2
    "t_600.hf", #3
    "t_700.hf", #4
    "t_800.hf", #5
    "t_900.hf", #6
    "t_950.hf", #7 
    "t_1000.hf", #8
    "t_1050.hf", #9
    "t_1100.hf", #10
    "t_1150.hf", #11
    "t_1200.hf", #12
    "t_1250.hf", #13 
    "t_1300.hf", #14
    "t_1350.hf", #15
    "t_1400.hf", #16
    "t_1450.hf", #17
    "t_1500.hf", #18
    "t_1550.hf", #19
    "t_1600.hf", #20
    "t_1650.hf", #21
    "t_1700.hf", #22
    "t_1750.hf", #23
    "t_1800.hf", #24
    "t_1850.hf", #25
    "t_1900.hf", #26
    "t_1950.hf", #27
    "t_2000.hf", #28
    "t_2050.hf", #29
    "t_2100.hf", #30
    "t_2150.hf", #31
    "t_2200.hf", #32
    "t_2250.hf", #33
    "t_2300.hf", #34
    "t_2350.hf", #35
    "t_2400.hf", #36
  ]
# 限界性能
# Large: 1800
# Orval: 1500
# 45: 1200 ~ 1350
# 135: ~1800
# 45_2: ~1550
# 135_2: ~1500
# V90: 1200　1150?
profile_idx_size: 19
# idx = mode選択時
profile_idx: [
    {
      # 0: 探索パラメータindex&最短 300
      run_param: 0,
      suction: 0,
      normal: 0,
      large: 0,
      orval: 0,
      dia45: 0,
      dia45_2: 0,
      dia135: 0,
      dia135_2: 0,
      dia90: 0,
    },
    {
      # 1: 最短パラメータ 400
      run_param: 1,
      suction: 0,
      normal: 1,
      large: 1,
      orval: 1,
      dia45: 1,
      dia45_2: 1,
      dia135: 1,
      dia135_2: 1,
      dia90: 1,
    },
    {
      # 2: 最短パラメータ 500
      run_param: 2,
      suction: 1,
      normal: 0,
      large: 2,
      orval: 2,
      dia45: 2,
      dia45_2: 2,
      dia135: 2,
      dia135_2: 2,
      dia90: 2,
    },
    {
      # 3: 最短パラメータ 600
      run_param: 3,
      suction: 1,
      normal: 0,
      large: 4,
      orval: 3,
      dia45: 3,
      dia45_2: 3,
      dia135: 3,
      dia135_2: 3,
      dia90: 3,
    },
    {
      # 4: 最短パラメータ 700
      run_param: 4,
      suction: 1,
      normal: 0,
      large: 4,
      orval: 4,
      dia45: 4,
      dia45_2: 4,
      dia135: 4,
      dia135_2: 4,
      dia90: 4,
    },
    {
      # 5: 最短パラメータ 800
      run_param: 5,
      suction: 1,
      normal: 0,
      large: 5,
      orval: 5,
      dia45: 5,
      dia45_2: 5,
      dia135: 5,
      dia135_2: 5,
      dia90: 5,
    },
    {
      # 6: 最短パラメータ 900
      run_param: 6,
      suction: 1,
      normal: 0,
      large: 6,
      orval: 6,
      dia45: 6,
      dia45_2: 6,
      dia135: 6,
      dia135_2: 6,
      dia90: 6,
    },
    {
      # 7: 最短パラメータ 950
      run_param: 7,
      suction: 1,
      normal: 0,
      large: 7,
      orval: 7,
      dia45: 7,
      dia45_2: 7,
      dia135: 7,
      dia135_2: 7,
      dia90: 7,
    },
    {
      # 8: 最短パラメータ 1000
      run_param: 8,
      suction: 1,
      normal: 0,
      large: 8,
      orval: 8,
      dia45: 8,
      dia45_2: 8,
      dia135: 8,
      dia135_2: 8,
      dia90: 8,
    },
    {
      # 9: 最短パラメータ 1050
      run_param: 9,
      suction: 1,
      normal: 0,
      large: 9,
      orval: 9,
      dia45: 9,
      dia45_2: 9,
      dia135: 9,
      dia135_2: 9,
      dia90: 9,
    },
    {
      # 10: 最短パラメータ 1100
      run_param: 10,
      suction: 1,
      normal: 0,
      large: 10,
      orval: 10,
      dia45: 10,
      dia45_2: 10,
      dia135: 10,
      dia135_2: 10,
      dia90: 10,
    },
    {
      # 11: 最短パラメータ 1150
      run_param: 11,
      suction: 1,
      normal: 0,
      large: 11,
      orval: 11,
      dia45: 11,
      dia45_2: 11,
      dia135: 11,
      dia135_2: 11,
      dia90: 11,
    },
    {
      # 12: 最短パラメータ 1200
      run_param: 12,
      suction: 1,
      normal: 0,
      large: 12,
      orval: 12,
      dia45: 12,
      dia45_2: 12,
      dia135: 12,
      dia135_2: 12,
      dia90: 12,
    },
    {
      # 13: 最短パラメータ 1250
      run_param: 12,
      suction: 1,
      normal: 0,
      large: 16,
      orval: 16,
      dia45: 16,
      dia45_2: 16,
      dia135: 16,
      dia135_2: 16,
      dia90: 16,
    },
    {
      # 14: 最短パラメータ 1300
      run_param: 14,
      suction: 2,
      normal: 16,
      large: 18,
      orval: 18,
      dia45: 18,
      dia45_2: 18,
      dia135: 18,
      dia135_2: 18,
      dia90: 18,
    },
    {
      # 15: 最短パラメータ 1350
      run_param: 15,
      suction: 2,
      normal: 0,
      large: 16,
      orval: 16,
      dia45: 16,
      dia45_2: 16,
      dia135: 16,
      dia135_2: 16,
      dia90: 16,
    },
    {
      # 16: 最短パラメータ 1400
      run_param: 16,
      suction: 2,
      normal: 0,
      large: 24,
      orval: 24,
      dia45: 24,
      dia45_2: 24,
      dia135: 24,
      dia135_2: 24,
      dia90: 24,
    },
    {
      # 17: 最短パラメータ 1450
      run_param: 17,
      suction: 2,
      normal: 0,
      large: 24,
      orval: 24,
      dia45: 24,
      dia45_2: 24,
      dia135: 24,
      dia135_2: 24,
      dia90: 24,
    },
    {
      # 18: 最短パラメータ 1500
      run_param: 18,
      suction: 2,
      normal: 0,
      large: 28,
      orval: 28,
      dia45: 28,
      dia45_2: 28,
      dia135: 26,
      dia135_2: 26,
      dia90: 26,
    },
    {
      # 19: 最短パラメータ 1500
      run_param: 19,
      suction: 2,
      normal: 0,
      large: 28,
      orval: 28,
      dia45: 28,
      dia45_2: 28,
      dia135: 26,
      dia135_2: 26,
      dia90: 26,
    },
    {
      # 20: 最短パラメータ 1500
      run_param: 20,
      suction: 2,
      normal: 0,
      large: 28,
      orval: 28,
      dia45: 28,
      dia45_2: 28,
      dia135: 26,
      dia135_2: 26,
      dia90: 26,
    },
    {
      # 21: 最短パラメータ 1500
      run_param: 21,
      suction: 2,
      normal: 0,
      large: 30,
      orval: 30,
      dia45: 30,
      dia45_2: 30,
      dia135: 28,
      dia135_2: 28,
      dia90: 26,
    },
    {
      # 22: 最短パラメータ 1500
      run_param: 22,
      suction: 2,
      normal: 0,
      large: 30,
      orval: 30,
      dia45: 30,
      dia45_2: 30,
      dia135: 28,
      dia135_2: 28,
      dia90: 26,
    },
    {
      # 23: 最短パラメータ 1500
      run_param: 23,
      suction: 2,
      normal: 0,
      large: 31,
      orval: 31,
      dia45: 30,
      dia45_2: 30,
      dia135: 30,
      dia135_2: 30,
      dia90: 26,
    },
    {
      # 24: 最短パラメータ 1500
      run_param: 24,
      suction: 2,
      normal: 0,
      large: 32,
      orval: 32,
      dia45: 30,
      dia45_2: 30,
      dia135: 30,
      dia135_2: 30,
      dia90: 26,
    },
    {
      # 25: 最短パラメータ 1500
      run_param: 24,
      suction: 2,
      normal: 0,
      large: 32,
      orval: 32,
      dia45: 30,
      dia45_2: 30,
      dia135: 30,
      dia135_2: 30,
      dia90: 26,
    },
    {
      # 26: 最短パラメータ 1500
      run_param: 24,
      suction: 2,
      normal: 0,
      large: 30,
      orval: 28,
      dia45: 24,
      dia45_2: 24,
      dia135: 23,
      dia135_2: 23,
      dia90: 23,
    },
    {
      # 27: 最短パラメータ 1500
      run_param: 24,
      suction: 2,
      normal: 0,
      large: 30,
      orval: 28,
      dia45: 24,
      dia45_2: 24,
      dia135: 23,
      dia135_2: 23,
      dia90: 23,
    },
    {
      # 28: 最短パラメータ 1500
      run_param: 24,
      suction: 2,
      normal: 0,
      large: 30,
      orval: 28,
      dia45: 24,
      dia45_2: 24,
      dia135: 23,
      dia135_2: 23,
      dia90: 23,
    },
  ]
